### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [taviso/ctypes.sh#10]
I would like to point out that identifiers like "[`__TYPES_H`](https://github.com/taviso/ctypes.sh/blob/6282db6ac683a0b910e7db0bb7e672e9b56132fc/types.h#L1)" and "[`__UTIL_H`](https://github.com/taviso/ctypes.sh/blob/c4f8adcf0e35b004d593c236d77b0274435e4a78/util.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by joshtriplett** [comment]
Alternatively, you could use "#pragma once", which the compilers on all of your target platforms support.

**Comment by elfring** [comment]
I prefer [standard-compliance](http://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/23699893#23699893 "Is #pragma once part of the C++11 standard?") a bit more.

**Comment by joshtriplett** [comment]
This software is already less portable than the C/C++ standards, and by necessity always will be.  The underlying libffi in particular supports a limited set of compilers.  Every one of those compilers supports "#pragma once", as do others.

In any case, the choice of how to address this (including not doing so at all, since these identifiers work just fine and are widely used) is up to the author at this point.

**Comment by taviso** [comment]
Point taken, I'll keep this in mind.
