### ISSUE TITLE
Associative Array Rehashing

### ISSUE THREAD

**Issue by taviso** [taviso/ctypes.sh#55]
I think in bash 5.1 struct support will break, because bash introduced an automatic rehashing feature.

bash used to allocate a fixed size hash table for every associative array, and it never changed for the life of the array. Now, if you add lots of items to the array, bash will dynamically rehash it with a more efficient bucket size.

This causes two problems:

1. The order of elements might change.
2. Any saved pointers might now become invalid.

This is a note to self to investigate solutions.

There doesn't seem to be an easy flag we can set, I asked on the mailing list and Chet seemed willing to add one, but not before 5.1 is released. I *think* a solution might be to just make our own alternative to `hash_create()`.... I dunno.

**Comment by ormaaj** [comment]
I haven't noticed this yet but probably will. Have to do more research to find a definite solution.

A potential mechanism might involve using the nameref and associative array together. You can abuse the "default zero index" (ordinarily it's a horrible misfeature) to store an indirect variable reference that resolves to somewhere else within the array, or another array. There are some interesting permutations on that which may partially overcome the disallowed use of `typeset -na`.

If all that's really needed is an ordered-set the usual obvious solution is to store values into the index, and you optionally have the string value available to store whatever. One might make use of the new-ish `asort` builtin to sort an array with its keys and values swapped.
 
I'm surprised bash continued using a linked-list for its own symbol table rather than switch to the hash table - I guess it must have an MRU cache similar to the indexed array, which would explain why my simple tests can't measure nonlinear changes in symbol lookup time with any number of variables.

**Comment by taviso** [comment]
I went ahead and tried this fix in 0604e0af82f939fc208945dac190b32aa84fa5ef.

I don't know if it's a perfect solution, but it seems to work and it's better than nothing!
